plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - docs/**/*
    - vendor/**/*
    - gemfiles/**/*
    - lib/generators/**/templates/**/*
  SuggestExtensions: false

Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Performance/CollectionLiteralInLoop:
  Exclude:
    - spec/**/*
Performance/RedundantBlockCall:
  Enabled: false # TODO: temporarily disabled to avoid potential breaking change
Performance/StringInclude:
  Exclude:
    - lib/ruby_llm/providers/**/capabilities.rb
Performance/UnfreezeString:
  Exclude:
    - spec/**/*
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
